name: Flutter Build
on: [push]

jobs:
  Build_Windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v4
        with:
          name: flutter-win
          path: .\build\windows\x64\runner\Release

  # Build_Android:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #     - run: flutter --version
  #     - run: flutter pub get
  #     - run: flutter build apk --release
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: flutter-apk
  #         path: .\build\app\outputs\flutter-apk\app-release.apk

  Build_Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - name: Install GTK dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
      - run: flutter build linux --release
      - uses: actions/upload-artifact@v4
        with:
          name: flutter-linux
          path: ./build/linux/x64/release/bundle
